start transaction ;
delete from public.cmdb_ci_people_rel;
delete from public.cmdb_ci_rel;
delete from public.cmdb_bu_people_rel;
delete from public.cmdb_people;
delete from public.cmdb_ci_attr;
delete from public.cmdb_ci_cluster;
delete from public.cmdb_ci_server;
delete from public.cmdb_ci_service;
delete from public.cmdb_path_product_rel;
delete from public.cmdb_path_ci_rel;
delete from public.cmdb_bu;
delete from public.cmdb_ci_people_rel_type where id between 2201 and 2205;
delete from public.cmdb_ci_ci_rel_type where id between 1201 and 1208;
delete from public.cmdb_state where id in (7201,7202,7203,8201,8202,9201,9202);
delete from public.cmdb_topology_path;
update public.cmdb_default_product_path set path_id = 0 where path_id in (456975363141632,457009452789760);
delete from public.cmdb_user where login_name = 'autoTest';
commit ;
